### ISSUE TITLE
Checklist for 0.2.7

### ISSUE THREAD

**Issue by weibeld** [weibeld/terraform-aws-kubeadm#18]
Changes to include in 0.2.7. The changes consists mainly of refactorings and small optimisations:

- [x] Make `cluster_name` a mandatory input variables, which allows eliminating the `random_pet` resource in the Terraform code
- [x] Remove `kubeconfig_dir` input variable
- [ ] Change default for `master_instance_type` input variable from `t2.medium` (2 CPUs, 4 GB RAM) to `t3.small` (2 CPUs, 2 GB RAM). kubeadm requires master nodes to have at least 2 CPUs and 1.7 GB RAM.
- [ ] Change default for `worker_instance_type` input variables to from `t2.small` (1 CPU, 2 GB RAM) to `t3.micro` (2 CPUs, 1 GB RAM). 
- [ ] Collapse security groups into two: one for all nodes (`egress`, `ingress-ssh`, `ingress-internal`) and one that's assigned additionally to the master node (`ingress-k8s`).
- [ ] Increase verbosity of `kubeadm` commands in bootstrap scripts (e.g. `-v 2`). The logs can be inspected on the nodes in `/var/log/cloud-init-output.log` (see [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html#user-data-shell-scripts))
- [ ] Add further log output to bootstrap script, e.g. for marking the beginnings of the individual commands
- [ ] Set hostname on nodes (see for example [here](https://thenewstack.io/how-to-deploy-kubernetes-with-kubeadm-and-containerd/)). Currently, the preflight checks on both master and worker nodes contain the following warnings:
    ```
    [preflight] Running pre-flight checks
            [WARNING Hostname]: hostname "master" could not be reached
            [WARNING Hostname]: hostname "master": lookup master on 127.0.0.53:53: server misbehaving
    ```
- [x] Update containerd installation in bootstrap scripts to install containerd directly and not via the `docker.io` package.
- [ ] Change Ubuntu version back to 22.04. The reason is that this is an LTS version (in contrast to 22.10) and the new installation method for containerd has also been verified to work on Ubuntu 22.04.

**Comment by weibeld** [comment]
Close this in favour of individual issues linked to the 0.2.7 milestone.
