### ISSUE TITLE
Checklist for 0.3.0

### ISSUE THREAD

**Issue by weibeld** [weibeld/terraform-aws-kubeadm#20]
New features and changes for 0.3.0:

- [ ] Allow selection of Kubernetes version (#1)
- [ ] When the Kubernetes bootstrapping fails, the run of the Terraform module should fail too. Currently, after the `kubeadm join` command fails, the `/home/ubuntu/done` file is still created and the Terraform module run completes successfully. Fix this by detecting failure in the bootstrapping code and signalising this to the Terraform module, e.g. by creating a file `/home/ubuntu/fail` instead of `/home/ubuntu/done`, and the Terraform module code also checking for this file.
- [ ] Prefix AWS resource names with `kubeadm` (instead of only tagging the resources)
- [ ] Change AWS resource tag prefix to `kubeadm` (instead of `terraform-kubeadm`)

**Comment by weibeld** [comment]
Close this in favour of individual issues linked to the 0.3.0 milestone.
