### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by weibeld** [weibeld/terraform-aws-kubeadm#6]
Requested features for v0.3:

- [x] Choose Kubernetes version (#1)
- [ ] Pass custom user data to EC2 instances (#2)
- [x] Add EC2 instance IDs to `cluster_nodes` output (#4)
- [ ] Add availability zone as input parameter (#4)
- [x] Add availability zone to `cluster_nodes` output (#4)
- [ ] Add support for autoscaling groups (#7)
- [ ] Additional SSH key options:
    1. Use an existing AWS EC2 key pair (specify name of key pair on AWS and private key file on local machine)
    2. Create keys on the fly (e.g. use [tls_private_key])(https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key)
    3. Provide both public and private key on the local machine (already implemented)
